// scripts/generateImageArrays.js
// Script to automatically generate image arrays from folders

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const IMAGE_FOLDERS_ROOT = path.join(__dirname, '../../public/galleries');
const OUTPUT_FILE = path.join(__dirname, '../data/imageGalleries.js');

// Supported image extensions
const IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.svg'];

/**
 * Check if a file is an image based on its extension
 */
function isImageFile(filename) {
  const ext = path.extname(filename).toLowerCase();
  return IMAGE_EXTENSIONS.includes(ext);
}

/**
 * Get all images from a directory
 */
function getImagesFromFolder(folderPath, relativePath = '') {
  try {
    const files = fs.readdirSync(folderPath);
    const images = [];

    files.forEach(file => {
      const fullPath = path.join(folderPath, file);
      const stat = fs.statSync(fullPath);

      if (stat.isDirectory()) {
        // Recursively get images from subdirectories
        const subImages = getImagesFromFolder(
          fullPath, 
          path.join(relativePath, file)
        );
        images.push(...subImages);
      } else if (isImageFile(file)) {
        // Add image with web-accessible path
        const webPath = `/galleries/${path.join(relativePath, file).replace(/\\/g, '/')}`;
        images.push(webPath);
      }
    });

    // Sort images alphabetically
    images.sort();
    return images;
  } catch (error) {
    console.error(`Error reading folder ${folderPath}:`, error.message);
    return [];
  }
}

/**
 * Generate galleries object from folder structure
 */
function generateGalleries() {
  const galleries = {};

  try {
    // Create root folder if it doesn't exist
    if (!fs.existsSync(IMAGE_FOLDERS_ROOT)) {
      console.log(`Creating galleries folder at: ${IMAGE_FOLDERS_ROOT}`);
      fs.mkdirSync(IMAGE_FOLDERS_ROOT, { recursive: true });
      return galleries;
    }

    const folders = fs.readdirSync(IMAGE_FOLDERS_ROOT);

    folders.forEach(folder => {
      const folderPath = path.join(IMAGE_FOLDERS_ROOT, folder);
      const stat = fs.statSync(folderPath);

      if (stat.isDirectory()) {
        const images = getImagesFromFolder(folderPath, folder);
        
        if (images.length > 0) {
          // Convert folder name to readable title
          const title = folder
            .replace(/[-_]/g, ' ')
            .replace(/\b\w/g, char => char.toUpperCase());

          galleries[folder] = {
            title,
            images,
            count: images.length
          };

          console.log(`✓ Found ${images.length} images in "${title}"`);
        }
      }
    });

    return galleries;
  } catch (error) {
    console.error('Error generating galleries:', error.message);
    return galleries;
  }
}

/**
 * Write galleries data to output file
 */
function writeGalleriesFile(galleries) {
  try {
    // Create output directory if it doesn't exist
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const fileContent = `// Auto-generated by scripts/generateImageArrays.js
// Do not edit manually - changes will be overwritten

export const galleries = ${JSON.stringify(galleries, null, 2)};

// Helper function to get gallery by key
export function getGallery(key) {
  return galleries[key];
}

// Get all gallery keys
export function getGalleryKeys() {
  return Object.keys(galleries);
}

// Get total number of galleries
export function getGalleryCount() {
  return Object.keys(galleries).length;
}
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf8');
    console.log(`\n✓ Generated galleries file at: ${OUTPUT_FILE}`);
    return true;
  } catch (error) {
    console.error('Error writing galleries file:', error.message);
    return false;
  }
}

/**
 * Main execution
 */
function main() {
  console.log('🖼️  Image Gallery Generator\n');
  console.log(`Scanning for images in: ${IMAGE_FOLDERS_ROOT}\n`);

  const galleries = generateGalleries();
  const galleryCount = Object.keys(galleries).length;

  if (galleryCount === 0) {
    console.log('\n⚠️  No galleries found.');
    console.log(`   Create folders in ${IMAGE_FOLDERS_ROOT} and add images.`);
    console.log('   Example structure:');
    console.log('   public/galleries/');
    console.log('   ├── vacation-2024/');
    console.log('   │   ├── photo1.jpg');
    console.log('   │   └── photo2.jpg');
    console.log('   └── portfolio/');
    console.log('       ├── project1.png');
    console.log('       └── project2.png');
  } else {
    console.log(`\n📊 Summary:`);
    console.log(`   Found ${galleryCount} ${galleryCount === 1 ? 'gallery' : 'galleries'}`);
    
    const totalImages = Object.values(galleries).reduce(
      (sum, gallery) => sum + gallery.count, 
      0
    );
    console.log(`   Total images: ${totalImages}`);
  }

  writeGalleriesFile(galleries);
  console.log('\n✨ Done!\n');
}

// Run the script
main();